name: Verify

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:    
      - apache5
      - jv11
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1.0.0
        with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: |
              ${{ runner.os }}-maven-
      - name: Build with Maven
        env:
          EMBOLD_URL: https://oss.emboldci.dev
          EMBOLD_TOKEN: ${{ secrets.EMBOLD_OSS_SCAN_TOKEN }}
        run: |
          mvn -B package io.embold.scan:embold-maven-plugin:embold -Dembold.host.url=https://oss.emboldci.dev -Dembold.user.token=${{ secrets.EMBOLD_OSS_SCAN_TOKEN }} --file pom.xml
          response=$(curl --silent --location --request GET "https://oss.emboldci.dev/api/v1/repositories/2dd6b50efbd23318bd3505d5029e1318/qualitygateprofiles/status" --header "Authorization:Bearer ${{ secrets.EMBOLD_OSS_SCAN_TOKEN }}")
          if [ "$response" != 'passed' ]; then
            RED='\033[0;31m'
            GREEN='\033[0;32m'
            NC='\033[0m' # No Color
            printf "Embold Quality gate ${RED}FAILED${NC}"
            exit 1
          fi
          printf "Embold Quality gate ${GREEN}PASSED${NC}"
