# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - emboldcli_test

  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8corona.tar.gz
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      # Runs a set of commands using the runners shell
      - name: Run with Embold CLI
        run: |
          echo "Run with Embold CLI"
          #curl --silent --location --request GET "http://192.168.2.38:3001/api/v1/packagedownload/corona?os=linux&checksum=null" --header "Authorization:Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYxODkzMzM5NjgxNCwiaWF0IjoxNjE4OTMzMzk2fQ.Vc1Gp4dlOSvyzc8UwcsGoaN88PE-cGFe39n2Qedmh-NokIW9F_31ZvRAli115MYz8rXEiJ6ay53AvV78yZq5cQ" -o corona.tar.gz
          curl --silent --location --request GET "https://oss.emboldci.dev/api/v1/packagedownload/corona?os=linux&checksum=null" --header "Authorization:Bearer ${{ secrets.EMBOLD_OSS_SCAN_TOKEN }}" -o corona.tar.gz
          tar -xf corona.tar.gz
          ls corona
          mkdir temp
          echo ${{ secrets.EMBOLD_OSS_SCAN_TOKEN }}
          cat ./corona/coronacli/config/cli.properties
          echo -e "embold.url=https://oss.emboldci.dev \nembold.token=${{ secrets.EMBOLD_OSS_SCAN_TOKEN }}" >| ./corona/coronacli/config/cli.properties
          echo -------------------------
          cat ./corona/coronacli/config/cli.properties
          export CORONA_HOME=./corona
          export CORONA_LOG=./corona/logs
          ./corona/coronacli/bin/coronacli -b "." -c "." -r "git" -p "./corona/coronacli/config/plugins_empty.xml" -d "./temp" -g
          
          
        
