# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - emboldcli_test

  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      # Runs a set of commands using the runners shell
      - name: Run with Embold CLI
        run: |
          echo "Run with Embold CLI"
          echo "test, and deploy your project."
