# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - emboldcli_test
    # Sequence of patterns matched against refs/heads
    branches-ignore:    
      - apache5
      - jv11
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run with Embold CLI
        run: |
          echo Run with Embold CLI
          echo test, and deploy your project.
